# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./rebedit.h
SOURCES += ./main.cpp \
    ./rebedit.cpp
FORMS += ./rebedit.ui
RESOURCES += rebedit.qrc
